# Generated by Django 3.1.2 on 2020-11-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('headquarters', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_company', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagesBackdrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backref_id', models.IntegerField(blank=True, null=True)),
                ('image_category', models.CharField(max_length=10)),
                ('image_data', models.TextField()),
                ('aspect_ratio', models.FloatField(blank=True, null=True)),
                ('heigth', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('iso_639_1', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'images_backdrops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagesPosters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backref_id', models.IntegerField(blank=True, null=True)),
                ('image_category', models.CharField(max_length=10)),
                ('image_data', models.TextField()),
                ('aspect_ratio', models.FloatField(blank=True, null=True)),
                ('heigth', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('iso_639_1', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'images_posters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('adult', models.BooleanField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(blank=True, max_length=10, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('original_title', models.CharField(blank=True, max_length=200, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('streamable', models.BooleanField()),
                ('torrent', models.BooleanField()),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('firbase_storage', models.BooleanField()),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoviesProductionCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movies_production_companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoviesToBackdrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movies_to_backdrops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoviesToGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movies_to_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoviesToPosters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movies_to_posters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoviesToTorrents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movies_to_torrents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('known_for_department', models.CharField(blank=True, max_length=200, null=True)),
                ('death_day', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.BinaryField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('adult', models.BooleanField(blank=True, null=True)),
                ('profile_picture_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeopleAlsoKnownAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'people_also_known_as',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceGoogleDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('backref_id', models.IntegerField()),
                ('size_bytes', models.IntegerField(blank=True, null=True)),
                ('preview_url', models.CharField(max_length=200)),
                ('sharing_url', models.CharField(max_length=200)),
                ('drive_file_id', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('drive_folder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'source_google_drive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Torrents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=15, null=True)),
                ('date_uploaded', models.DateField(blank=True, null=True)),
                ('seeds', models.IntegerField(blank=True, null=True)),
                ('peers', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('magent_url', models.TextField(blank=True, null=True)),
                ('hash', models.TextField(blank=True, null=True)),
                ('torrent_file', models.BinaryField(blank=True, null=True)),
                ('torrent_source', models.CharField(blank=True, max_length=20, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('size_bytes', models.IntegerField(blank=True, null=True)),
                ('torrent_category', models.TextField(blank=True, null=True)),
                ('backref_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'torrents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('full_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_picture', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
