# Generated by Django 3.1.2 on 2020-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('backref_id', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_accessed', models.DateTimeField()),
            ],
            options={
                'db_table': 'user__favourites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('backref_id', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_accessed', models.DateTimeField()),
            ],
            options={
                'db_table': 'user__history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('backref_id', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('last_accessed', models.DateTimeField()),
            ],
            options={
                'db_table': 'user__watchlist',
                'managed': False,
            },
        ),
    ]
